name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  TestExpressionConverter:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make TestExpressionConverter
    - name: execute tests
      run: ./a.exe
    - name: cleanup
      run: make clean
