name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  TestScanner:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make -f tests/Scanner/Makefile
    - name: execute tests
      run: ./a.exe
    - name: cleanup
      run: make clean
